### ISSUE TITLE
Integrate Crowsoucing and Group modules

### ISSUE THREAD

**Issue by pedrorocha-net** [Minka/minka#18]
Make sure that Ideas integrate with Group seamlessly. If necessary, create a sub-module "crowdsourcing_group"

**Comment by victorcpereira** [comment]
In the group type setting page, we can see the content tab. 
I installed the plugin "Group node (Idea)". 
It provides the ability to add an "Idea" to the group.

Maybe later we will need the module "crowdsourcing_group"
But for now, it's just what we need.
